name: ${DOCKER_COMPOSE_PROJECT_NAME}

services:
  nuxt:
    build: .
    # restart: always
    ports:
      - ":3000"
    # command: "npm run start"
    labels:
      - traefik.enable=true
      - traefik.http.routers.xmrchatnuxt.rule=Host(`${DOMAIN_NAME:-xmrchat.com}`)
      - traefik.http.routers.xmrchatnuxt.entrypoints=websecure
      - traefik.http.routers.xmrchatnuxt.tls=true
      - traefik.http.routers.xmrchatnuxt.tls.certresolver=myresolver
      - traefik.http.services.xmrchatnuxt.loadbalancer.server.port=3000
    networks:
      - traefik
    env_file: .env
networks:
  traefik:
    name: traefik
    external: true
