services:
  posgtres:
    image: postgres:14-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - ${REDIS_PORT}:6379

    volumes:
      - ./redis/data:/data

  minio:
    image: quay.io/minio/minio
    ports:
      - ${MINIO_PORT}:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}

    volumes:
      - ./minio/data:/data

    command: server /data --console-address ":9001"

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
