services:
  nuxt:
    build: .
    container_name: xmrchat-nuxt-new
    restart: always
    ports:
      - "3001:3000"
    # command: "npm run start"
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.xmrchatnew-nuxt.rule=Host(`new.xmrchat.com`)
      - traefik.http.routers.xmrchatnew-nuxt.entrypoints=websecure
      - traefik.http.services.xmrchatnew-nuxt.loadbalancer.server.port=3000
      - "traefik.http.routers.xmrchatnew-nuxt.tls=true"
      - "traefik.http.routers.xmrchatnew-nuxt.tls.certresolver=myresolver"
    networks:
      - traefik
    env_file: .env
networks:
  traefik:
    name: traefik
    external: true
